import { BillingPlan } from "@prisma/client";

// Define a list of features that are tied to subscription plans
export enum Feature {
  BASIC_POST_SCHEDULING = "BASIC_POST_SCHEDULING",
  ADVANCED_POST_SCHEDULING = "ADVANCED_POST_SCHEDULING",
  CONNECT_SOCIAL_ACCOUNTS_BASIC = "CONNECT_SOCIAL_ACCOUNTS_BASIC", // e.g., 1 account
  CONNECT_SOCIAL_ACCOUNTS_PRO = "CONNECT_SOCIAL_ACCOUNTS_PRO", // e.g., up to 10 accounts
  CONNECT_SOCIAL_ACCOUNTS_ENTERPRISE = "CONNECT_SOCIAL_ACCOUNTS_ENTERPRISE", // Unlimited accounts
  BASIC_POST_ANALYTICS = "BASIC_POST_ANALYTICS",
  ADVANCED_ANALYTICS = "ADVANCED_ANALYTICS",
  TEAM_COLLABORATION = "TEAM_COLLABORATION",
  ROLE_MANAGEMENT = "ROLE_MANAGEMENT",
  BASIC_APPROVAL_WORKFLOWS = "BASIC_APPROVAL_WORKFLOWS",
  ADVANCED_APPROVAL_WORKFLOWS = "ADVANCED_APPROVAL_WORKFLOWS",
  AI_CONTENT_ASSISTANT = "AI_CONTENT_ASSISTANT",
  UNIFIED_INBOX = "UNIFIED_INBOX",
  CUSTOM_INTEGRATIONS_API_ACCESS = "CUSTOM_INTEGRATIONS_API_ACCESS",
  ADVANCED_SECURITY_COMPLIANCE = "ADVANCED_SECURITY_COMPLIANCE",
  SLA_GUARANTEE = "SLA_GUARANTEE",
  CUSTOM_BRANDING = "CUSTOM_BRANDING",
  DEDICATED_ACCOUNT_MANAGER = "DEDICATED_ACCOUNT_MANAGER",
  MEDIA_STORAGE_BASIC = "MEDIA_STORAGE_BASIC", // e.g., 1 GB
  MEDIA_STORAGE_PRO = "MEDIA_STORAGE_PRO", // e.g., 100 GB
  MEDIA_STORAGE_UNLIMITED = "MEDIA_STORAGE_UNLIMITED", // Unlimited
  PRIORITY_EMAIL_SUPPORT = "PRIORITY_EMAIL_SUPPORT",
  EMAIL_SUPPORT = "EMAIL_SUPPORT",
}

// Define the minimum BillingPlan required for each feature
export const FEATURE_MIN_PLAN: Record<Feature, BillingPlan> = {
  [Feature.BASIC_POST_SCHEDULING]: BillingPlan.FREE,
  [Feature.ADVANCED_POST_SCHEDULING]: BillingPlan.PRO,
  [Feature.CONNECT_SOCIAL_ACCOUNTS_BASIC]: BillingPlan.FREE,
  [Feature.CONNECT_SOCIAL_ACCOUNTS_PRO]: BillingPlan.PRO,
  [Feature.CONNECT_SOCIAL_ACCOUNTS_ENTERPRISE]: BillingPlan.ENTERPRISE,
  [Feature.BASIC_POST_ANALYTICS]: BillingPlan.FREE,
  [Feature.ADVANCED_ANALYTICS]: BillingPlan.PRO,
  [Feature.TEAM_COLLABORATION]: BillingPlan.PRO,
  [Feature.ROLE_MANAGEMENT]: BillingPlan.PRO,
  [Feature.BASIC_APPROVAL_WORKFLOWS]: BillingPlan.PRO,
  [Feature.ADVANCED_APPROVAL_WORKFLOWS]: BillingPlan.ENTERPRISE,
  [Feature.AI_CONTENT_ASSISTANT]: BillingPlan.PRO,
  [Feature.UNIFIED_INBOX]: BillingPlan.PRO,
  [Feature.CUSTOM_INTEGRATIONS_API_ACCESS]: BillingPlan.ENTERPRISE,
  [Feature.ADVANCED_SECURITY_COMPLIANCE]: BillingPlan.ENTERPRISE,
  [Feature.SLA_GUARANTEE]: BillingPlan.ENTERPRISE,
  [Feature.CUSTOM_BRANDING]: BillingPlan.ENTERPRISE,
  [Feature.DEDICATED_ACCOUNT_MANAGER]: BillingPlan.ENTERPRISE,
  [Feature.MEDIA_STORAGE_BASIC]: BillingPlan.FREE,
  [Feature.MEDIA_STORAGE_PRO]: BillingPlan.PRO,
  [Feature.MEDIA_STORAGE_UNLIMITED]: BillingPlan.ENTERPRISE,
  [Feature.PRIORITY_EMAIL_SUPPORT]: BillingPlan.PRO,
  [Feature.EMAIL_SUPPORT]: BillingPlan.FREE,
};

// Plan ranking for comparison (higher number = higher tier)
export const PLAN_RANKS: Record<BillingPlan, number> = {
  [BillingPlan.FREE]: 1,
  [BillingPlan.PRO]: 2,
  [BillingPlan.ENTERPRISE]: 3,
};
